/*
 * HSRM Wallbox API
 * This REST-API serves as a interface to a ISO-15118 SECC Server for vehicle to grid communication between an electric vehicle and a charging station. Over this API new charging sessions can be created and controlled. The API propeses methods to control the charging parameters during a charging session.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: fabian.birk@student.hs-rm.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.v2gclarity.risev2g.secc.wallboxServerEndpoint.rest.openapi.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * CommunicationSessionSessionIdStatusDuration
 */
@JsonPropertyOrder({
  CommunicationSessionSessionIdStatusDuration.JSON_PROPERTY_HOURS,
  CommunicationSessionSessionIdStatusDuration.JSON_PROPERTY_MINUTES,
  CommunicationSessionSessionIdStatusDuration.JSON_PROPERTY_SECONDS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2021-03-14T10:53:36.676157800+01:00[Europe/Berlin]")
public class CommunicationSessionSessionIdStatusDuration   {
  public static final String JSON_PROPERTY_HOURS = "hours";
  @JsonProperty(JSON_PROPERTY_HOURS)
  private Integer hours;

  public static final String JSON_PROPERTY_MINUTES = "minutes";
  @JsonProperty(JSON_PROPERTY_MINUTES)
  private Integer minutes;

  public static final String JSON_PROPERTY_SECONDS = "seconds";
  @JsonProperty(JSON_PROPERTY_SECONDS)
  private Integer seconds;

  public CommunicationSessionSessionIdStatusDuration hours(Integer hours) {
    this.hours = hours;
    return this;
  }

  /**
   * Get hours
   * @return hours
   **/
  @JsonProperty("hours")
  @ApiModelProperty(value = "")
  
  public Integer getHours() {
    return hours;
  }

  public void setHours(Integer hours) {
    this.hours = hours;
  }

  public CommunicationSessionSessionIdStatusDuration minutes(Integer minutes) {
    this.minutes = minutes;
    return this;
  }

  /**
   * Get minutes
   * @return minutes
   **/
  @JsonProperty("minutes")
  @ApiModelProperty(value = "")
  
  public Integer getMinutes() {
    return minutes;
  }

  public void setMinutes(Integer minutes) {
    this.minutes = minutes;
  }

  public CommunicationSessionSessionIdStatusDuration seconds(Integer seconds) {
    this.seconds = seconds;
    return this;
  }

  /**
   * Get seconds
   * @return seconds
   **/
  @JsonProperty("seconds")
  @ApiModelProperty(value = "")
  
  public Integer getSeconds() {
    return seconds;
  }

  public void setSeconds(Integer seconds) {
    this.seconds = seconds;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommunicationSessionSessionIdStatusDuration communicationSessionSessionIdStatusDuration = (CommunicationSessionSessionIdStatusDuration) o;
    return Objects.equals(this.hours, communicationSessionSessionIdStatusDuration.hours) &&
        Objects.equals(this.minutes, communicationSessionSessionIdStatusDuration.minutes) &&
        Objects.equals(this.seconds, communicationSessionSessionIdStatusDuration.seconds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hours, minutes, seconds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommunicationSessionSessionIdStatusDuration {\n");
    
    sb.append("    hours: ").append(toIndentedString(hours)).append("\n");
    sb.append("    minutes: ").append(toIndentedString(minutes)).append("\n");
    sb.append("    seconds: ").append(toIndentedString(seconds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

